apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: metrics
  name: metrics
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics
    spec:
      containers:
        - args:
            - -label=4
            - -metrics=1
            - -value=10
            - -value-len=20
            - -label-len=20
          command:
            - /metrics
          image: ccr.ccs.tencentyun.com/ccr_dev/metrics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          name: metrics
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
